package main

import (
	"testing"
)

func TestRun(t *testing.T) {
	expected := 34
	got := Run(`............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`)
    if got != expected {
        t.Errorf("Run = %d; expected %d", got, expected)
    }
}

func TestRun2(t *testing.T) {
	expected := 9
	got := Run(`T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........`)
    if got != expected {
        t.Errorf("Run = %d; expected %d", got, expected)
    }
}
